Product/config/routes.rb
Rails.application.routes.draw do
  get 'google_login_api/callback'
  root 'quizzes#index'
  
  # ログイン関連
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'

  # ユーザー登録ページ
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # その他ユーザー関連
  resources :users, only: %i[edit update show destroy]

  # 一覧以外の問題関連
  resources :quizzes, only: %i[edit new create update show destroy] do
    # 回答
    resources :answers, only: :create
  end

  # 検索
  get '/quizzes', to: 'quizzes#search', as: 'search_quizzes'

  # 表示件数
  resources :quizzes, only: [:index] do
    collection do
      get 'show_10'
      get 'show_30'
    end
  end

  # Google認証
  post '/google_login_api/callback', to: 'google_login_api#callback'
end

Product/app/views/layouts/_header.html.erb
<!-- app/views/layouts/_header.html.erb -->
<nav class="bg-gray-800 p-4">
  <div class="container mx-auto flex justify-between items-center">
    <%= link_to root_path, class: 'flex items-center text-white font-semibold text-lg' do %>
      <%= image_tag 'logo.png', alt: 'Logo', class: 'h-8 mr-2' %>
      QuizTech
    <% end %>

    <div class="flex items-center">
      <% if logged_in? %>
        <div class="flex items-center mr-4">
          <%= link_to current_user.name, user_path(current_user), class: 'text-white font-semibold mr-2' %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'px-4 py-2 mx-2 rounded-lg bg-red-500 text-white font-semibold' %>
        </div>
        <%= link_to '問題作成', new_quiz_path, class: 'px-4 py-2 mx-2 rounded-lg bg-blue-500 text-white font-semibold' %>
      <% else %>
        <%= link_to 'ログイン', login_path, class: 'px-4 py-2 mx-2 rounded-lg bg-blue-500 text-white font-semibold' %>
        <%= link_to '登録', signup_path, class: 'px-4 py-2 mx-2 rounded-lg bg-green-500 text-white font-semibold' %>
      <% end %>
    </div>
  </div>
</nav>

Product/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz for engineer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="flash-messages">
      <% flash.each do |type, message| %>
        <div class="bg-gray-100 border-t-4 <% if type == 'notice' %>border-blue-500<% elsif type == 'success' %>border-green-500<% elsif type == 'error' %>border-red-500<% end %> p-4 text-gray-800">
          <p><%= message %></p>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>