Product/config/routes.rb
Rails.application.routes.draw do
  get 'google_login_api/callback'
  root 'quizzes#index'
  
  # ログイン関連
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'

  # ユーザー登録ページ
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # その他ユーザー関連
  resources :users, only: %i[edit update show destroy]

  # 一覧以外の問題関連
  resources :quizzes, only: %i[edit new create update show destroy] do
    # 回答
    resources :answers, only: :create
  end

  # 検索
  get '/quizzes', to: 'quizzes#search', as: 'search_quizzes'

  # 表示件数
  resources :quizzes, only: [:index] do
    collection do
      get 'show_10'
      get 'show_30'
    end
  end

  # Google認証
  post '/google_login_api/callback', to: 'google_login_api#callback'
end

Product/app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :quiz_categories, dependent: :destroy
  has_many :categories, through: :quiz_categories

  validates :difficulty, presence: true
  validates :problem_statement, presence: true
  validates :first_option, presence: true
  validates :second_option, presence: true
  validates :third_option, presence: true
  validates :correct_option, presence: true, inclusion: { in: [1, 2, 3] }

  def correct_rate
    return 0 if answer_count == 0

    (correct_count.to_f / answer_count * 100).round(2)
  end

  # 正答率による難易度設定
  def set_difficulty
    # 正答率を計算
    accuracy = correct_rate

    # 正答率に応じて難易度を設定
    case accuracy
    when 80..100
      1
    when 60...80
      2
    when 40...60
      3
    when 20...40
      4
    else
      5
    end
  end
end

Product/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :require_login, except: [:show, :index, :search]

  def index
    if params[:per_page] == '30'
      @quizzes = Quiz.page(params[:page]).per(30)
    else
      @quizzes = Quiz.page(params[:page]).per(10)
    end
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = current_user.quizzes.build(quiz_params)
    if @quiz.save
      redirect_to quiz_path(@quiz), notice: "問題を作成しました。"
    else
      puts @quiz.errors.full_messages
      render :new
    end
  end

  def show
    @quiz = Quiz.find(params[:id])
    @correct_rate = @quiz.correct_rate
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    if @quiz.update(quiz_params)
      redirect_to @quiz, notice: "問題を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to user_path(@quiz.user), notice: "問題を削除しました。", status: :see_other
  end

  # モデルに定義するべき？
  def search
    keyword = params[:search]
    category = params[:category]

    @quizzes = Quiz.joins(:categories)

    # 問題文とカテゴリー名の部分一致検索
    if keyword.present? && category.present?
      @quizzes = @quizzes.where('problem_statement LIKE ? OR categories.name LIKE ?', "%#{keyword}%", "%#{category}%")
    elsif keyword.present?
      @quizzes = @quizzes.where('problem_statement LIKE ?', "%#{keyword}%")
    elsif category.present?
      @quizzes = @quizzes.where('categories.name LIKE ?', "%#{category}%")
    end

    # ページネーションを再設定
    @quizzes = @quizzes.page(params[:page]).per(params[:per_page] || 10)

    render :index
  end

  private

  def quiz_params
    correct_option = params[:correct_option].to_i
    params.require(:quiz).permit(
      :problem_statement,
      :first_option,
      :second_option,
      :third_option,
      :correct_option,
      category_ids: []
    ).merge(correct_option: correct_option)
  end

end

Product/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

Product/app/views/quizzes/edit.html.erb
<!-- app/views/quizzes/edit.html.erb -->
<div class="container mt-4">
  <h2 class="text-xl font-semibold mb-4">問題編集</h2>

  <%= form_with model: @quiz, url: quiz_path(@quiz), method: :patch, local: true, data: { controller: "quiz-form" } do |f| %>
    <div class="mb-4">
      <%= f.label :problem_statement, "問題文", class: "font-semibold" %>
      <%= f.text_area :problem_statement, class: "rounded-lg p-2 border border-gray-200 bg-white w-full", rows: 4 %>
    </div>

    <div class="mb-4">
      <%= f.label :first_option, "選択肢1", class: "font-semibold" %>
      <div class="flex items-center">
        <%= f.text_field :first_option, class: "rounded-lg p-2 border border-gray-200 bg-white w-full" %>
        <%= radio_button_tag "correct_option", "1", @quiz.correct_option == 1, class: "ml-2 option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <label for="correct_option_1" class="ml-1">正解</label>
      </div>
    </div>

    <div class="mb-4">
      <%= f.label :second_option, "選択肢2", class: "font-semibold" %>
      <div class="flex items-center">
        <%= f.text_field :second_option, class: "rounded-lg p-2 border border-gray-200 bg-white w-full" %>
        <%= radio_button_tag "correct_option", "2", @quiz.correct_option == 2, class: "ml-2 option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <label for="correct_option_2" class="ml-1">正解</label>
      </div>
    </div>

    <div class="mb-4">
      <%= f.label :third_option, "選択肢3", class: "font-semibold" %>
      <div class="flex items-center">
        <%= f.text_field :third_option, class: "rounded-lg p-2 border border-gray-200 bg-white w-full" %>
        <%= radio_button_tag "correct_option", "3", @quiz.correct_option == 3, class: "ml-2 option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <label for="correct_option_3" class="ml-1">正解</label>
      </div>
    </div>

    <div class="mb-4">
      <%= f.label :category_ids, "カテゴリ", class: "font-semibold" %>
      <%= f.collection_select :category_ids, Category.all, :id, :name, { prompt: "カテゴリを選択" }, { class: "rounded-lg p-2 border border-gray-200 bg-white" } %>
    </div>

    <div class="text-center">
      <%= f.submit '更新', class: 'px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold' %>
    </div>
  <% end %>
</div>

Product/app/views/quizzes/index.html.erb
<div class="container mt-4">
  <h2 class="text-xl font-semibold mb-4">問題一覧</h2>

  <div class="flex justify-center mb-4">
    <!-- 問題検索フォーム -->
    <%= form_with url: search_quizzes_path, model: @quiz, method: :get, class: "w-full max-w-md flex" do |f| %>
      <div class="flex border rounded-lg w-full"> <!-- 入力フォームの範囲を最大化 -->
        <%= f.text_field :search, value: params[:search], placeholder: "問題検索", class: "w-full pr-16 p-2 border-none bg-transparent focus:outline-none" %>
      </div>
      <div class="ml-2">
        <button type="submit" class="px-4 py-2 bg-blue-500 text-white font-semibold rounded-lg">検索</button>
      </div>
    </div>

      <div class="mt-2">
        <%= f.label :category, "カテゴリー", class: "font-semibold" %>
        <%= f.select :category, options_for_select(Category.all.pluck(:name), params[:category]), { include_blank: true }, class: "w-48 p-2 border rounded-lg bg-white" %>
      </div>
    <% end %>
  </div>

  <%= turbo_frame_tag "cats-list" do %>
    <% @quizzes.each do |quiz| %>
      <div class="bg-white p-4 rounded-lg shadow-md mb-4">
        <h3 class="text-lg font-semibold mb-2">
          <%= link_to quiz.problem_statement, quiz_path(quiz), class: "text-blue-500 font-semibold hover:underline" %>
        </h3>
      </div>
    <% end %>
  <% end %>

  <!-- ページネーションリンク -->
  <div class="flex justify-center mt-4">
    <nav class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
      <%= paginate @quizzes, previous_label: '前へ', next_label: '次へ', class: 'pagination hover:text-blue-600 text-lg' %>
    </nav>
  </div>
</div>

Product/app/views/quizzes/new.html.erb
<div class="container mt-4">
  <h2 class="text-xl font-semibold mb-4">問題作成</h2>

  <%= form_with model: @quiz, url: quizzes_path, local: true, data: { controller: "quiz-form" } do |f| %>
    <div class="mb-4">
      <%= f.label :problem_statement, "問題文", class: "font-semibold" %>
      <%= f.text_area :problem_statement, class: "rounded-lg p-2 border border-gray-200 bg-white w-full", rows: 4 %>
    </div>

    <div class="mb-4">
      <%= f.label :first_option, "選択肢1", class: "font-semibold" %>
      <div class="flex items-center">
        <%= f.text_field :first_option, class: "rounded-lg p-2 border border-gray-200 bg-white w-full" %>
        <%= radio_button_tag "correct_option", "1", false, class: "ml-2 option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <label for="correct_option_1" class="ml-1">正解</label>
      </div>
    </div>

    <div class="mb-4">
      <%= f.label :second_option, "選択肢2", class: "font-semibold" %>
      <div class="flex items-center">
        <%= f.text_field :second_option, class: "rounded-lg p-2 border border-gray-200 bg-white w-full" %>
        <%= radio_button_tag "correct_option", "2", false, class: "ml-2 option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <label for="correct_option_2" class="ml-1">正解</label>
      </div>
    </div>

    <div class="mb-4">
      <%= f.label :third_option, "選択肢3", class: "font-semibold" %>
      <div class="flex items-center">
        <%= f.text_field :third_option, class: "rounded-lg p-2 border border-gray-200 bg-white w-full" %>
        <%= radio_button_tag "correct_option", "3", false, class: "ml-2 option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <label for="correct_option_3" class="ml-1">正解</label>
      </div>
    </div>

    <div class="mb-4">
      <%= f.label :category_ids, "カテゴリ", class: "font-semibold" %>
      <%= f.collection_select :category_ids, Category.all, :id, :name, { prompt: "カテゴリを選択" }, { class: "rounded-lg p-2 border border-gray-200 bg-white" } %>
    </div>

    <%= f.submit '問題作成', class: 'px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold' %>
  <% end %>
</div>

Product/app/views/quizzes/show.html.erb
<div class="container mt-4 flex flex-col items-center">

  <div class="mb-4 text-center">
    <h2 class="text-xl font-semibold">
      作成者: <%= link_to @quiz.user.name, user_path(@quiz.user), class: "text-blue-500 hover:underline" %>
    </h2>
  </div>

  <div class="mb-4">
    <h2 class="text-xl font-semibold">カテゴリ: <%= @quiz.categories.pluck(:name).join(", ") %></h2>
  </div>

  <div class="mb-4">
    <h2 class="text-xl font-semibold">問題文</h2>
    <p class="text-lg"><%= @quiz.problem_statement %></p>
  </div>

  <div class="mb-4 flex">
    <% if current_user == @quiz.user %>
      <%= link_to "編集", edit_quiz_path(@quiz), class: "px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold mr-2" %>
      <%= button_to "削除する", quiz_path(@quiz), method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: "px-4 py-2 rounded-lg bg-red-500 text-white font-semibold" %>
    <% end %>
  </div>

  <%= form_with(model: @quiz.answers.new, url: quiz_answers_path(@quiz)) do |f| %>
    <div class="mb-4">
      <label class="flex items-center">
        <%= radio_button_tag "answer[option]", "1", false, class: "option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <span class="ml-2 text-lg"><%= @quiz.first_option %></span>
      </label>
    </div>

    <div class="mb-4">
      <label class="flex items-center">
        <%= radio_button_tag "answer[option]", "2", false, class: "option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <span class="ml-2 text-lg"><%= @quiz.second_option %></span>
      </label>
    </div>

    <div class="mb-4">
      <label class="flex items-center">
        <%= radio_button_tag "answer[option]", "3", false, class: "option-radio", data: { controller: "quiz-form-for-show", action: "click->quiz-form-for-show#selectOption" } %>
        <span class="ml-2 text-lg"><%= @quiz.third_option %></span>
      </label>
    </div>

    <%= f.submit "回答", class: "px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold" %>
  <% end %>
</div>